# Generated by Django 4.2.7 on 2023-11-05 22:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_alter_group_curator"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="name",
            new_name="group",
        ),
    ]
